sudo: required
dist: trusty
language: bash

stages:
  - name: Terraform run
  - name: Perform tests
  - name: Deploy code
    if: branch = master && type != cron  

services:
  - docker

install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-get -qq update
  - sudo apt-get -t trusty-backports install shellcheck
  - sudo pip install awscli  
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.5/terraform_0.12.5_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

jobs:
  include:
    - stage: Perform tests
      script:
        - echo "Check for commit ${TRAVIS_COMMIT} and tag ${TRAVIS_TAG} from branch ${TRAVIS_BRANCH}."
        - echo "This is build number ${TRAVIS_BUILD_NUMBER}, for ${TRAVIS_REPO_SLUG}."
        - mkdir /tmp/config-custom
        - docker pull almerhor/pylint:default
        - docker run --rm -v $(pwd):/pylint -v $(pwd)/test:/tmp/config-custom almerhor/pylint:default py/cloud_control_create_ec2.py requirements-custom.txt
    
    - stage: Perform tests
      dist: trusty
      language: java
      sudo: required
      addons:
        sonarcloud:
          organization: "alexa-cloud-control"
          token: 
            secure: "Rs0YO1hVG4wMmspKFiWiFdJJeYSGAJG+cA9heb/kwbVJQleVZxb0jF0i5JOQ09MvgYcDExGROSiXj+69XVvfDZTDfmSYxEpmtgQzL0i8wo462dmD5KY+XRcU+nZqjuOFc1Xkjk2q+foo6Wb8tUBcNjh9gwAStWFv5qlicZn76iP54SeahoqHf6jnVi9lZntCpFbxfnjXNnLyY2WoNka/O4COmUU9TPmIL6APCouFCiSimD9QNrkoUh43fGvc69spnfFL373BlOma11AWlkNe35J9I9CZO92Ocx8VH4nAvSFX4aJ+5LCYLREvmf+pUpaHRm0xPI6XV/ee6hbOdC0D2BmrL30DKWx0Z697tmBMoQdz4f/ZIRyd/r2JljVL4FqbTPMaFvrYMwwFBYBgQ9Qota9NnzjNdbScjzjGxQ3B1Q5Y/MJ75VpYjMMJPEmvhTdnaBdJzoQTq5zbWLXHmdnY7ZwU9DtlYIqUlaOdMRel0PkFiKxqHAlWNUAR3WRDBfgDJdwbY5ItCRP9aQu6Dg2eppL6i1eP17uIu00hFrhz45/6RqoiiAVZglJ2xzG0Ju8slbu1tX8UlNYj7kig/RVNOO73eCvxwfUBg08g54pANs1efoRQ4XAWavl5QcjNyay8n3M24pkO/XoC59BgATsGoFziDovmSRPxJgbo3czLSJU="
      
      jdk:
        - oraclejdk8

      script:
        - sudo chmod +x $(which sonar-scanner)
        - export PATH=$(dirname $(which sonar-scanner)):$PATH
        - sonar-scanner

    - stage: Terraform run
      env:
        - TF_INPUT=false # No interraction
      script:
        - cd provision
        - echo "Feeding terraform.tf with variables."
        - sed -i -e "s/STATEBUCKETNAME/${terraform_bucket}/g" terraform.tf_template
        - sed -i -e "s/TABLENAME/${terraform_table}/g" terraform.tf_template
        - sed -i -e "s/REGION/${terraform_region}/g" terraform.tf_template
        - mv terraform.tf_template terraform.tf
        - echo "Feeding terraform.tfvars with variables."
        - sed -i -e "s/REGION/${terraform_region}/g" terraform.tfvars_template
        - sed -i -e "s/TABLENAME/${terraform_table}/g" terraform.tfvars_template
        - sed -i -e "s/STATEBUCKETNAME/${terraform_bucket}/g" terraform.tfvars_template
        - sed -i -e "s/ARTIFACTBUCKETNAME/${artifact_bucket}/g" terraform.tfvars_template
        - sed -i -e "s/ENVIRONMENT/${terraform_environment}/g" terraform.tfvars_template
        - sed -i -e "s/CONTEXTTABLENAME/${dynamodb_context}/g" terraform.tfvars_template
        - mv terraform.tfvars_template terraform.tfvars
        - terraform init
        - terraform validate
        - ./execute.sh

    - stage: Deploy code
      script: skip
      deploy:
        - provider: s3
          bucket: "${artifact_bucket}"
          local_dir: py
          skip_cleanup: true

        - provider: lambda
          function_name: "cloud_control_create_ec2"
          region: "${terraform_region}"
          role: "arn:aws:iam::${account_number}:role/LambdaAlexaCloudControlCreateEc2IamRole"
          runtime: "python3.6"
          module_name: "cloud_control_create_ec2"
          handler_name: "cloud_control_create_ec2"
          description: "Alexa EC2 - Create EC2"
          memory_size: 128
          timeout: 5
          zip: py/cloud_control_create_ec2.py
          environment_variables: table=${dynamodb_context}
          function_tags: {"Name"="cloud_control_create_ec2","Project"="Alexa Cloud Control"}

